# Generated by Django 6.0.3 on 2026-04-13 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttackApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('blocked', 'Blocked'), ('review', 'Review')], default='safe', max_length=20)),
                ('wazuh_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('phishing', 'Phishing'), ('login', 'Login'), ('url_flag', 'Suspicious URL'), ('scan', 'System Scan'), ('brute_force', 'Brute Force'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('successful', 'Successful'), ('flagged', 'Flagged'), ('completed', 'Completed'), ('detected', 'Detected')], max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('wazuh_rule_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('health_percentage', models.FloatField(default=100.0)),
                ('status', models.CharField(default='Optimal', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('wazuh_agents_connected', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
            },
        ),
        migrations.CreateModel(
            name='ThreatDetected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wazuh_alert_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('threat_type', models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('brute_force', 'Brute Force'), ('sql_injection', 'SQL Injection'), ('ddos', 'DDoS'), ('other', 'Other')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('blocked', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='WazuhSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('alerts_fetched', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.RemoveField(
            model_name='alert',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='scanned_by',
        ),
        migrations.AlterModelOptions(
            name='threatlevel',
            options={'ordering': ['-percentage']},
        ),
        migrations.RemoveField(
            model_name='threatlevel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='threatlevel',
            name='level',
        ),
        migrations.AddField(
            model_name='threatlevel',
            name='color',
            field=models.CharField(default='#00ffcc', max_length=20),
        ),
        migrations.AddField(
            model_name='threatlevel',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='threatlevel',
            name='threat_type',
            field=models.CharField(default='threat_type', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BlockedAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('attack_vector', models.CharField(max_length=100)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule_id', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AttackApp.threatdetected')),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
